// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using adv.Data;

#nullable disable

namespace adv.Migrations
{
    [DbContext(typeof(DataDBContext))]
    partial class DataDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("adv.Model.model", b =>
                {
                    b.Property<string>("UNIQUEPERSONKEY")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DATEOFBIRTH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMAIL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FIRSTNAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GENDER")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LASTNAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MIDDLEINITIAL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PERMANENTADDRESSLINE1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PERMANENTADDRESSLINE2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PERMANENTCITY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PERMANENTCOUNTRY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PERMANENTSTATE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PERMANENTZIPCODE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TELEPHONENUMBER")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UNIQUEPERSONKEY");

                    b.ToTable("Member");
                });

            modelBuilder.Entity("adv.Model.model2", b =>
                {
                    b.Property<int>("PROVIDERID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PROVIDERID"));

                    b.Property<string>("CONTRACTED")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FIRSTNAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HPSPECIALITYCODE1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LASTNAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MIDDLEINITIAL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PAYORID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TAXONOMYCODE1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PROVIDERID");

                    b.ToTable("Provider");
                });

            modelBuilder.Entity("adv.Model.model3", b =>
                {
                    b.Property<string>("MEMBERNUMBER")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PROVIDERID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QUANTITY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RXDAYSSUPPLY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RXFILLDATA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UNITSOFMEASURE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MEMBERNUMBER");

                    b.ToTable("Pharmacy");
                });
#pragma warning restore 612, 618
        }
    }
}
